name: Pull Request

on:
  pull_request:
    branches: [master, release]

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Snyk code scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
        with:
          command: code test --all-sub-projects --severity-threshold=medium

  scan-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Snyk dependency scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
        with:
          args: --all-sub-projects --severity-threshold=high

  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20.x']
        os: [ubuntu-latest]
    env:
      CI: 1
      NPM_TOKEN: ${{ secrets.NPM_RO_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable --no-progress --ignore-scripts

      - name: Verify
        run: make verify
